---
name: reviewdog

on:
  pull_request:

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: detect-secrets
      uses: ./
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        workdir: testdata

  detect-secrets-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: detect-secrets
      uses: ./
      with:
        detect_secrets_version: "1.3.0"
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        workdir: testdata
