---
name: reviewdog

on:
  pull_request:

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: detect-secrets
      uses: ./
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        detect_secrets_flags: --all-files --force-use-all-plugins --exclude-files '(.git/|testdata/config.yaml|application).*'
