---
name: update-semver

on:
  push:
    branches-ignore:
    - "**"
    tags:
    - v*.*.*

jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: haya14busa/action-update-semver@v1
      with:
        github_token: ${{ secrets.github_token }}
